# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='pic_folder/profile/None/no-img.png', upload_to='pic_folder/profile/'),
        ),
    ]
